In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [3]:
# loading the dataset to a pandas DataFrame
dataset = pd.read_csv('data2.csv')

In [4]:
# printing the first 5 rows of the dataset
dataset.head()

,gender,age,hypertension,smoking_history,bmi,Urinating_often,Chest_ pain,Tremor,upper_abdomain_pain,prognosis,covid,drinking,place
0,1,80.0,0,0,25.19,0,0,0,0,Diabetes,0,1,rural
1,1,54.0,0,0,27.32,1,0,0,0,Diabetes,1,1,urban
2,0,28.0,0,0,27.32,1,0,0,0,Diabetes,0,0,urban
3,1,36.0,0,1,23.45,0,0,0,0,Diabetes,1,0,urban
4,0,76.0,1,1,20.14,1,0,0,0,Diabetes,0,0,urban

In [5]:
dataset.size

13923

In [6]:
dataset['place']=encoder.fit_transform(dataset['place'])

In [7]:
dataset.head(100)

,gender,age,hypertension,smoking_history,bmi,Urinating_often,Chest_ pain,Tremor,upper_abdomain_pain,prognosis,covid,drinking,place
0,1,80.0,0,0,25.19,0,0,0,0,Diabetes,0,1,0
1,1,54.0,0,0,27.32,1,0,0,0,Diabetes,1,1,1
2,0,28.0,0,0,27.32,1,0,0,0,Diabetes,0,0,1
3,1,36.0,0,1,23.45,0,0,0,0,Diabetes,1,0,1
4,0,76.0,1,1,20.14,1,0,0,0,Diabetes,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,19.0,0,0,27.32,0,0,0,0,Diabetes,1,1,1
96,1,67.0,0,0,27.32,0,0,0,0,Diabetes,1,1,1
97,0,11.0,0,0,27.32,1,0,0,0,Diabetes,1,1,0
98,1,30.0,0,0,50.13,1,0,0,0,Diabetes,1,0,1
99,0,29.0,0,1,27.32,0,0,0,0,Diabetes,1,1,1

In [8]:
# getting the statistical measures of the data
dataset.describe()

,gender,age,hypertension,smoking_history,bmi,Urinating_often,Chest_ pain,Tremor,upper_abdomain_pain,covid,drinking,place
count,1071.000000,1071.000000,1071.000000,1071.000000,1071.000000,1071.000000,1071.000000,1071.000000,1071.000000,1071.000000,1071.000000,1071.000000
mean,0.586368,41.199514,0.066293,0.170868,26.916256,0.335201,0.210084,0.160598,0.091503,0.519141,0.517274,0.548086
std,0.492714,22.966820,0.248910,0.376570,6.715787,0.472281,0.407558,0.367331,0.288458,0.499867,0.499935,0.497915
min,0.000000,0.080000,0.000000,0.000000,10.300000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,22.000000,0.000000,0.000000,22.840000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,42.000000,0.000000,0.000000,27.320000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
75%,1.000000,59.000000,0.000000,0.000000,29.015000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
max,1.000000,80.000000,1.000000,1.000000,69.370000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
dataset.head()

,gender,age,hypertension,smoking_history,bmi,Urinating_often,Chest_ pain,Tremor,upper_abdomain_pain,prognosis,covid,drinking,place
0,1,80.0,0,0,25.19,0,0,0,0,Diabetes,0,1,0
1,1,54.0,0,0,27.32,1,0,0,0,Diabetes,1,1,1
2,0,28.0,0,0,27.32,1,0,0,0,Diabetes,0,0,1
3,1,36.0,0,1,23.45,0,0,0,0,Diabetes,1,0,1
4,0,76.0,1,1,20.14,1,0,0,0,Diabetes,0,0,1

In [10]:
# number of rows and Columns in this dataset
dataset.shape

(1071, 13)

In [11]:
dataset['prognosis'].value_counts()

Parkinsons_disease    280
Gastritis             273
Diabetes              259
Heart_disease         259
Name: prognosis, dtype: int64

In [12]:
dataset.groupby('prognosis').mean()

,gender,age,hypertension,smoking_history,bmi,Urinating_often,Chest_ pain,Tremor,upper_abdomain_pain,covid,drinking,place
prognosis,,,,,,,,,,,,
Diabetes,0.606178,41.577297,0.061776,0.150579,27.120425,0.621622,0.189189,0.000000,0.000000,0.536680,0.494208,0.610039
Gastritis,0.560440,41.726300,0.058608,0.172161,26.509597,0.000000,0.000000,0.000000,0.358974,0.498168,0.553114,0.534799
Heart_disease,0.559846,41.818996,0.069498,0.181467,26.695290,0.196911,0.679537,0.000000,0.000000,0.505792,0.505792,0.559846
Parkinsons_disease,0.617857,39.763429,0.075000,0.178571,27.328286,0.525000,0.000000,0.614286,0.000000,0.535714,0.514286,0.492857

In [13]:
# separating the data and labels
X = dataset.drop(columns = 'prognosis', axis=1)
Y = dataset['prognosis']

In [14]:
print(Y)

0        Diabetes
1        Diabetes
2        Diabetes
3        Diabetes
4        Diabetes
          ...
1066    Gastritis
1067    Gastritis
1068    Gastritis
1069    Gastritis
1070    Gastritis
Name: prognosis, Length: 1071, dtype: object

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify=Y, random_state=2)

In [16]:
print(X.shape, X_train.shape, X_test.shape)

(1071, 12) (856, 12) (215, 12)

In [17]:
classifier = svm.SVC(kernel='linear')

In [18]:
dataset['place']=encoder.fit_transform(dataset['place'])

In [19]:
#training the support vector Machine Classifier
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [20]:
# accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [21]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.6904205607476636

In [22]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [23]:
# accuracy score on the test data
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.7348837209302326

In [24]:
input_data = (1,69,0,0,21.24,1,0,0,0,1,1,0)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = classifier.predict(input_data_reshaped)
print(prediction)

if (prediction == 'Diabetes'):
  print('The person has Diabetes')
elif (prediction == 'Heart disease'):
  print('The person has Heart disease')
elif (prediction == 'Parkinsons disease'):
  print('The person has Parkinsons disease')
else:
  print('The person has Gastritis')

['Diabetes']
The person has Diabetes

In [25]:
import pickle

In [26]:
filename = 'prognosis2_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [27]:
# loading the saved model
loaded_model = pickle.load(open('prognosis2_model.sav', 'rb'))

In [28]:
input_data = (0,0,0,0,21.24,0,0,0,0,0,0,0)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = classifier.predict(input_data_reshaped)
print(prediction)

if (prediction == 'Diabetes'):
  print('The person has Diabetes')
elif (prediction == 'Heart disease'):
  print('The person has Heart disease')
elif (prediction == 'Parkinsons_disease'):
  print('The person has Parkinsons disease')
else:
  print('The person has Gastritis')

['Gastritis']
The person has Gastritis

In [29]:
for column in X.columns:
  print(column)

gender
age
hypertension
smoking_history
bmi
Urinating_often
Chest_ pain
Tremor
upper_abdomain_pain
covid
drinking
place